name: Caching Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create File
        run: echo "$(date)" > DemoFile.txt

      - name: Cache DemoFile.txt
        id: demo-cache-id
        uses: actions/cache@v3
        env:
          cache-name: cache-demo-file
        with:
          path: DemoFile.txt
          key: ${{ hashFiles('cache-dependency-file.txt') }}

      - name: Print Content of DemoFile
        run: cat DemoFile.txt

      - name: Cache Found
        if: ${{ steps.demo-cache-id.outputs.cache-hit == 'true' }}
        run: echo "Cache Found"

      - name: Cache Not Found
        if: ${{ steps.demo-cache-id.outputs.cache-hit != 'true' }}
        run: echo "Cache Not Found"
